version: "3"
services:


  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    ports:
      - "8080:80"
    links:
      - "mysql:db"
    depends_on:
      - mysql
  mysql:
    image: mysql
    environment:
      - MYSQL_ROOT_PASSWORD=test123
    volumes:
      - "./mysql/data:/var/lib/mysql:rw"
  apache:
    image: php:7-apache
    ports:
      - "8081:80"
    links:
      - mysql
    volumes:
      - "../backend/web:/var/www/html:rw"
    depends_on:
      - mysql



